name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: The ref to checkout from.
        required: true
        default: 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.ref }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
